name: Statiq
description: Static blogging made easy
markdown: redcarpet
pygments: true
permalink: /:year/:month/:day/:title/
paginate: 5
url: file:///Users/aharris88/Documents/statiq/_site
email: zarin@builtbyhq.com